services:
  - type: worker
    name: trading-gpt-agent
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: KRAKEN_API_KEY
        sync: false
      - key: KRAKEN_API_SECRET
        sync: false
